version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: milky-awards-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - milky-awards-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: milky-awards-backend
    env_file:
      - ./.env
    environment:
      - DB_HOST=postgres
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      [postgres]    
    networks:
      - milky-awards-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  milky-awards-network:
    driver: bridge

